### PR TITLE
Added Youtube Video Downloader

### PR DESCRIPTION
**Pull request by CS-Aditya-Rawat**

### CODE REVIEW

**Comment by Veershah26** [comment]
Hey @CS-Aditya-Rawat , So i checked the code and it does work, but the url is already described in the code, can you like add a little segement for the user to enter custom URL ?

**Comment by CS-Aditya-Rawat** [comment]
Check it now, I have changed it and mark the PR under hactoberfest-accepted. 
Thanks

**Comment by Veershah26** [comment]
Ggs, it's good now. Merging the PR, thank you

**Comment by CS-Aditya-Rawat** [comment]
Please mark it under hacktoberfest-accepted.

**Pull request merged**
